### ISSUE TITLE
请问requirements中的cycle是打错了嘛？

### ISSUE THREAD

**Issue by zhijianren** [hackerchenzhuo/KTeleBERT#2]
cycle是指的是cycler库吗？

**Comment by zhijianren** [comment]
cycle很早就不维护了，甚至还在用Python2的语法

**Comment by hackerchenzhuo** [comment]
打应该是没打错..当时直接拉下来的，请问是安装过程出问题了吗？

**Comment by zhijianren** [comment]
![image](https://github.com/hackerchenzhuo/KTeleBERT/assets/35862976/cafee411-29e3-4f76-9bf4-bf93eedd6d3c)
这个cycle的Python库是装不了的，大佬。
![image](https://github.com/hackerchenzhuo/KTeleBERT/assets/35862976/eb12d535-a76e-4af2-a38c-c3b7b2ee0cf4)
您看是这个吗，2015年就不更新了

**Comment by hackerchenzhuo** [comment]
额，可能是我记错了，itertools是Python的一个内置模块

<img width="762" alt="image" src="https://github.com/hackerchenzhuo/KTeleBERT/assets/42081540/8aa03b27-7b07-4d69-b50b-89cf59d5dcb8">

**Comment by zhijianren** [comment]
噢噢，好的，感谢大佬

**Comment by hackerchenzhuo** [comment]
客气了，感谢指正
